version: "3"

services:
  pubsub:
    image: knarz/pubsub-emulator
    environment:
      - PUBSUB_PROJECT_ID=test-project
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    restart: always
    ports:
      - "8085:8085"